name: Mise à jour EDT

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-calendar:

    runs-on: ubuntu-latest

    steps:

      - name: Récupérer le dépôt
        uses: actions/checkout@v5

      - name: Installer Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: |
          pip install icalendar recurring-ical-events

      - name: Récupérer le calendrier Apple
        env:
          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}
        run: |
          python fetch_calendar.py

      - name: Vérifier calendar.json
        run: |
          echo "Contenu de calendar.json :"
          cat calendar.json

      - name: Enregistrer le nouveau calendrier
        run: |
          git config user.name "EDT Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add calendar.json

          if git diff --cached --quiet; then
            echo "Aucune modification du calendrier."
          else
            git commit -m "Mise à jour EDT"
            git push
          fi
